---
version: '3'
services:
  server:
    build: .
    image: index.docker.io/oaklabs/component-webcam:${VERSION-latest}
    network_mode: host
    environment:
      - PORT=9101
    ports:
      - "9000-9999:9000-9999"
    devices:
      - /dev/video0